Extension { #name : 'RowanSample9V3TestCase' }

{ #category : 'tests' }
RowanSample9V3TestCase >> testCiv1 [  self assert: RowanSample9V3Class1 civ1 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testCiv2 [  self assert: RowanSample9V3Class1 civ2 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testCv1 [  self assert: RowanSample9V3Class1 new cv1 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testCv2 [  self assert: RowanSample9V3Class1 new cv2 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testIv1 [  self assert: RowanSample9V3Class1 new iv1 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testIv2 [  self assert: RowanSample9V3Class1 new iv2 = nil
]
