"
I am an example class
"
Class {
	#name : 'RowanSample9V3Class1',
	#superclass : 'Object',
	#instVars : [
		'iv1'
	],
	#classVars : [
		'Cv1'
	],
	#classInstVars : [
		'civ1'
	],
	#traits : 'RowanSample9V3Trait1',
	#classTraits : 'RowanSample9V3Trait1 classTrait',
	#category : 'RowanSample9V3-C01'
}

{ #category : 'accessing' }
RowanSample9V3Class1 class >> civ1 [ ^ civ1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> cv1 [ ^ Cv1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> iv1 [ ^ iv1
]
