Extension { #name : 'RowanSample9V3TestCase' }

{ #category : 'tests' }
RowanSample9V3TestCase >> testCiv2 [  self assert: RowanSample9V3Class1 civ2 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testCv2 [  self assert: RowanSample9V3Class1 new cv2 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testIv2 [  self assert: RowanSample9V3Class1 new iv2 = nil
]

{ #category : 'tests' }
RowanSample9V3TestCase >> testIv5 [  self assert: RowanSample9V3Class1 new iv5 = nil
]
