Trait {
	#name : 'RowanSample9V3Trait1',
	#instVars : [
		'iv2'
	],
	#classInstVars : [
		'civ2'
	],
	#classVars : [
		'Cv2'
	],
	#category : 'RowanSample9V3-Tr03',
	#package : 'RowanSample9V3-Tr03'
}

{ #category : 'accessing' }
RowanSample9V3Trait1 class >> civ2_t [ ^ civ2
]

{ #category : 'accessing' }
RowanSample9V3Trait1 >> cv2_t [ ^ Cv2
]

{ #category : 'accessing' }
RowanSample9V3Trait1 >> iv2_t [ ^ iv2
]
